### PR TITLE
adds mergify file

### PR DESCRIPTION
**Pull request by octonato**

### CODE REVIEW

**Comment by octonato** [comment]
I will rebase this with #77. We first need a working build.

**Comment by octonato** [comment]
This contains now the same mergify file as define in the TLS project. 

I will write a script in TemplateControl to add mergify to all templates.

**Comment by marcospereira** [comment]
> I will write a script in TemplateControl to add mergify to all templates.

There is a copy task already. For example:

https://github.com/lightbend/templatecontrol/blob/798b0a796f3efa6450f8b13b6986364f1090a931/src/main/resources/2.6.x.conf#L6-L12

**Review by dwijnand — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
> There is a copy task already. For example:

perfect, I was planning to add a shell script. That's much better.

**Pull request merged**
